### ISSUE TITLE
Analytical Look Over

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/sciencelabs-python#103]
Go through literally everything and catch as many of the little things as we can. Also, this is a good time to suggest any little touch ups that we would like to do.

**Comment by c-schwarze** [comment]
- [ ] test

**Comment by c-schwarze** [comment]
Most of these things are up for discussion. These are my notes of things that might be worth looking at.

- [ ] Change the table headings "Minutes" in the reports to be something more meaningful. Maybe "total time"?
- [ ] Change how the button works on [session reports](https://tutorlabs.bethel.edu/cslab/report/session/12273) "View by Course" and "View by Name".
- [ ] ^ on that same page, we should add a default value for "View by Course", if there are no users.
- [ ] We should probably consider using "Bethel" time formats. Look at the [Bethel Calendar](https://www.bethel.edu/events/calendar/) to get an idea of what that means.
- [ ] The [Course report](https://tutorlabs.bethel.edu/cslab/report/course) has a lot of shortened table names. I think that is fine, as otherwise the table would be too large. Lets think about either removing columns or adding some kind of hover functionality so that Unq, becomes Unique Students (or whatever it stands for).
- [ ] Have real pages for errors - 403, 404, 5XXs
- [ ] On the [student report](https://tutorlabs.bethel.edu/cslab/report/student/40086) and the cumulative view, the tables have a scrollbar, even though they don't need it (at normal sizes).
- [ ] I tried to change the semester for this [student](https://tutorlabs.bethel.edu/cslab/report/student/40086), and it sent a 500 error. I believe its due to there being no data for the student. (sentry error was triggered)
- [ ] [Cumulative report](https://tutorlabs.bethel.edu/cslab/report/annual) has the years listed as 2001-2002, but they are on 2 lines. This causes it to be hard to scan.
- [ ] The semester selector only goes back to 2005, but data goes back to 2001.
- [ ] The unscheduled session in the [monthly report](https://tutorlabs.bethel.edu/cslab/report/month/2019/2) has ??? for the total. Is that the value we want?
- [ ] The [monthly report](https://tutorlabs.bethel.edu/cslab/report/month/2019/2) has the month selectors in a different spot than the [session reports](https://tutorlabs.bethel.edu/cslab/report/session)
- [ ] [Session reports](https://tutorlabs.bethel.edu/cslab/report/session) "show tutor" functionality splits most tutors' names onto multiple lines. Its tough to read. Anything we can do to help that?

**Comment by c-schwarze** [comment]
- [ ] [Session reports](https://tutorlabs.bethel.edu/cslab/report/session) is there a reason these aren't deep linkable?
- [ ] [Course report](https://tutorlabs.bethel.edu/cslab/report/course/1024) is Nathan Gossett's course actually section 70? That seems weird.
- [ ] On the [Sessions page](https://tutorlabs.bethel.edu/cslab/session/), I think there are some columns that we don't need to sort by. For example, the buttons.
- [ ] Editing sessions - the "Date (click to select)" field is formatting oddly. This should probably be adjusted.
- [ ] If a session [doesn't have comments](https://tutorlabs.bethel.edu/cslab/session/edit/12315), it appears as "None". This should be handled better. 
- [ ] In [sessions](https://tutorlabs.bethel.edu/cslab/session/closed), the Available Sessions and Closed Sessions have differing orders of the columns. 
- [ ] Also, the Closed Sessions is formatted lower overall, due to the session selector. Anything we should do about that?
- [ ] When you edit or create a session, the semester selector changes the session. This definitely shouldn't happen (i think?)
- [ ] When adding a user that already exists, the message is vague. It doesn't tell you whether its a user already active, or if it activated a user.
- [ ] [Editing users](https://tutorlabs.bethel.edu/cslab/user/admin/40144) - The "User's Courses for Current Term" is formatted oddly. Maybe bold it or give it more visual space or make it a heading.
- [ ] The [Schedule](https://tutorlabs.bethel.edu/cslab/schedule/) tab table is formatted oddly - the edit and delete buttons are stacked.
- [ ] Create new schedule. The wording on the right for the "Session" button. That probably should just be a normal link to the session tab.
- [ ] On the schedule tab, Should there be more spacing for the courses? Or formatted more cleanly?
- [ ] On the [Email tab](https://tutorlabs.bethel.edu/cslab/email/create), why do the CC and BCC have ... after them?
- [ ] Email tab, why are the CC and BCC fields indented?
- [ ] Should the "Recipients" field be renamed to be "Recipient group" or something? I was expecting a list of users when i clicked it, due to the name.
- [ ] The [View Role](https://tutorlabs.bethel.edu/cslab/user/view-role) page, the wording says "website". That should probably say the name of the lab. Also in the comments.


It is a lot of comments, but 90% are simple fixes or discussions.

**Comment by c-schwarze** [comment]
I think there might be some more stress testing, and that should be done on xp. Trying to change the semester selector on pages, trying to deeplink to things that don't exist, etc.
