### ISSUE TITLE
alerts not showing on pages that are redirected/reloaded

### ISSUE THREAD

**Issue by bam95899** [betheluniversity/sciencelabs-python#129]
title says it all, some examples of where alerts are declared but don't visually occur are in the `create_session_submit` method and the `create_schedule_submit` method.

**Comment by j-jasik** [comment]
Fixed with PR #130 merge

**Comment by j-jasik** [comment]
I was just clicking through the site and I realized that this solved one problem but created another... Since we calling the methods directly now instead of doing a redirect it changed the routes. So for example after you create a session it used to send it to create_session_submit and then redirect to closed-sessions. However, now the route is create_session_submit since that method just calls the route directly. This not only looks weird, but it's also messing with the navigations since we determine the "active" one based on the url. We need to look at this fix again, and I'm tempted to revert it and start over. @c-schwarze @bam95899 thoughts? Nothing is really broken, but it doesn't look very good either.

**Comment by j-jasik** [comment]
I think I found a fix. If we go back to using redirects, but then add a line to the set_alert method that says flask_session.modified = True it recognizes the change and allows the alert to persist through the redirect. I'm going to move ahead with this.
